### ISSUE TITLE
the problem of train.py

### ISSUE THREAD

**Issue by XiandaGuo** [seoungwugoh/RGMP#18]
why do not you use bptt_hsm in train.py?  what is the meaning of ntokens in line 134 of train.py?  looking forward your replay!Thank you very much

**Comment by Starboy-at-earth** [comment]
I have encountered the same problem. Look forward to that the author can give some explanation, thank you in advance.

**Comment by zgf6781882** [comment]
I've run the training code, but I get very bad results, so I always encounter the following problems. 
Traceback (most recent call last):
  File "train.py", line 301, in <module>
    writer.add_scalar('Train/IOU', iou(torch.cat((1-all_E, all_E), dim=1), all_M), i + epoch * iters_per_epoch)
  File "/_guifangzhang/vos/RGMP/utils.py", line 93, in iou
    return i / u
ZeroDivisionError: float division by zero

 Does anyone encounter the same situation???

**Comment by gbc-sid** [comment]
I have the same iou problem and the segment results are bad. Have you solved this problem?
